apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flux-web-access
  namespace: flux-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: flux-operator
      app.kubernetes.io/instance: flux-operator
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
        - ipBlock:
            cidr: 192.168.252.0/24
        - ipBlock:
            cidr: 10.42.0.0/16
      ports:
        - port: 9080
          protocol: TCP
