apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: lab-ollama-model-config
  namespace: kagent
spec:
  model: llama3.2
  provider: Ollama
  ollama:
    host: http://ollama.kagent.svc.cluster.local:11434
    options:
      num_ctx: "8192"
